spring.application.name=autosusbcali
spring.datasource.url=jdbc:postgresql://localhost:5432/servicios_db
spring.datasource.username=servicios_user
spring.datasource.password=servicios_password
spring.datasource.driver-class-name=org.postgresql.Driver